<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="IronScheme.Core" Version="1.0.603" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Scripting\" />
    </ItemGroup>

</Project>
